{ pkgs, ... }:
{
  home.packages = with pkgs; [
    bat
    binutils
    btop
    bun
    cmake
    docker
    docker-compose
    duckdb
    exempi
    exiftool
    exiv2
    eza
    fd
    fenix.stable.toolchain
    file
    fzf
    gcc
    gh
    git
    glibcLocales
    gnumake
    gnutar
    go
    gopls
    gping
    grafana-alloy
    gum
    intel-media-driver
    jq
    jwt-cli
    kubernetes-helm
    libgcc
    libva
    libva-utils
    mesa
    micro
    mongosh
    mpv
    neovim
    nerd-fonts.jetbrains-mono
    nil
    nixd
    nixfmt
    nodejs_24
    opencode
    openssl.dev
    openstack-rs
    openstackclient-full
    opentofu
    p7zip
    packer
    patchelf
    pkg-config
    podman
    podman-compose
    ripgrep
    sops
    ssh-to-age
    strace
    # terragrunt
    tmux
    trufflehog
    unzip
    uv
    uxplay
    vulkan-tools
    winetricks
    wineWow64Packages.waylandFull
    wl-clipboard-rs
    xz
    yarn
    yq
    zip
    zoxide
    zstd

    (python312.withPackages (pypkgs: with pypkgs; [ ]))
    (ruby.withPackages (ps: with ps; [ license_finder ]))

    (google-cloud-sdk.withExtraComponents [
      google-cloud-sdk.components.kubectl
      google-cloud-sdk.components.gke-gcloud-auth-plugin
      google-cloud-sdk.components.package-go-module
    ])
  ];
}
